version: '3.1'
services:
  codeigniter:
    image: aspendigital/codeigniter:latest
    volumes:
      - './:/var/www/html/'
    ports:
      - '80:80'
    links:
      - mysql
  mysql:
    image: mysql:5.5
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=Alteclansing123
      - MYSQL_DATABASE=assistone
