version: '3.1'
services:
  codeigniter:
    image: aspendigital/codeigniter:latest
    container_name: assistone_test
    volumes:
      - './:/var/www/html/'
    links:
      - mysql
  mysql:
    image: mysql:5.5
    restart: always
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=Alteclansing123
      - MYSQL_DATABASE=assistone

networks:
  default:
    external:
      name: assistone-net
